### ISSUE TITLE
Question on the function `merge_prefactor` and `Base.+`

### ISSUE THREAD

**Issue by peter0627ustc** [numericalEFT/FeynmanDiagram.jl#89]
I found that the function `merge_prefactor` (in #58) has to confronted the different cases below and it seems a little messy, for `g=propagator(𝑓⁺(1)𝑓⁻(2), factor=1)`:
(a)`k1=(1*g+2*g)`
(b)`k2= linear_combination(g,g,1,2)`
The structures of them are different:
(1) For `k1`: 
![k1](https://user-images.githubusercontent.com/88972512/206915826-3f0f7c9a-7282-4312-a323-52f4b0db7205.png)
(2) For `k2`:
![k2](https://user-images.githubusercontent.com/88972512/206915849-cf9daa7a-7232-4a4e-ba73-bfbe26d8d61d.png)
I suggest these two cases should be unified to the second one in the `Base.+` function.

**Comment by dcerkoney** [comment]
This is the job of functions `prune_unary` and `merge_chains`. We should have `isequiv(prune_unary(k1), k2, :id)`. 
I agree that we probably want to call `prune_unary` and `merge_chains` directly in Base.+ and Base.* to clean up trees like `k1` immediately after construction.
